//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audits
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public int WindowId { get; set; }
        public string Accion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Clave { get; set; }
        public string Entidad { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Windows Windows { get; set; }
    }
}
