//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransitoEntities : DbContext
    {
        public TransitoEntities()
            : base("name=TransitoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Audits> Audits { get; set; }
        public virtual DbSet<CallCenterTurns> CallCenterTurns { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<LicenseClasses> LicenseClasses { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<MedicalPersons> MedicalPersons { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Processes> Processes { get; set; }
        public virtual DbSet<ProcessLogs> ProcessLogs { get; set; }
        public virtual DbSet<Rols> Rols { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<SectorWorkflows> SectorWorkflows { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<Terminals> Terminals { get; set; }
        public virtual DbSet<Trackings> Trackings { get; set; }
        public virtual DbSet<Turns> Turns { get; set; }
        public virtual DbSet<TypesLicenses> TypesLicenses { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Windows> Windows { get; set; }
        public virtual DbSet<Workflows> Workflows { get; set; }
        public virtual DbSet<Nighborhoods> Nighborhoods { get; set; }
    }
}
