//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licenses()
        {
            this.LicenseClasses = new HashSet<LicenseClasses>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> FechaOtorgamiento { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> TypesLicenseId { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string Firma { get; set; }
        public Nullable<int> TurnId { get; set; }
        public string NroRegistro { get; set; }
    
        public virtual People People { get; set; }
        public virtual Turns Turns { get; set; }
        public virtual TypesLicenses TypesLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseClasses> LicenseClasses { get; set; }
    }
}
