//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int Id { get; set; }
        public int WindowId { get; set; }
        public int RolId { get; set; }
        public bool Consulta { get; set; }
        public bool AltaModificacion { get; set; }
        public bool Baja { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Rols Rols { get; set; }
        public virtual Windows Windows { get; set; }
    }
}
