//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLogs
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Name { get; set; }
        public bool IsOk { get; set; }
        public string ErrorDescripcion { get; set; }
        public int ProcessId { get; set; }
    
        public virtual Processes Processes { get; set; }
    }
}
