//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectorWorkflows
    {
        public int Orden { get; set; }
        public int SectorID { get; set; }
        public int WorkflowID { get; set; }
    
        public virtual Sectors Sectors { get; set; }
        public virtual Workflows Workflows { get; set; }
    }
}
