//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string Texto1 { get; set; }
        public string Texto2 { get; set; }
        public Nullable<int> Numero1 { get; set; }
        public Nullable<int> Numero2 { get; set; }
        public Nullable<bool> Logico1 { get; set; }
        public Nullable<bool> Logico2 { get; set; }
        public Nullable<System.DateTime> Fecha1 { get; set; }
        public Nullable<System.DateTime> Fecha2 { get; set; }
    }
}
