//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trackings
    {
        public int Id { get; set; }
        public int TurnID { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.TimeSpan> Tiempo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CantidadDeLlamados { get; set; }
        public Nullable<int> StatusID { get; set; }
        public bool Alerta { get; set; }
        public bool Enable { get; set; }
        public int Orden { get; set; }
    
        public virtual Sectors Sectors { get; set; }
        public virtual Status Status { get; set; }
        public virtual Terminals Terminals { get; set; }
        public virtual Turns Turns { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
