//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeadoraTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turns()
        {
            this.Licenses = new HashSet<Licenses>();
            this.MedicalPersons = new HashSet<MedicalPersons>();
            this.Trackings = new HashSet<Trackings>();
        }
    
        public int Id { get; set; }
        public string Turno { get; set; }
        public int TypesLicenseID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.TimeSpan> Tiempo { get; set; }
        public bool Enable { get; set; }
        public Nullable<int> CallCenterTurnId { get; set; }
    
        public virtual CallCenterTurns CallCenterTurns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licenses> Licenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalPersons> MedicalPersons { get; set; }
        public virtual People People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trackings> Trackings { get; set; }
        public virtual TypesLicenses TypesLicenses { get; set; }
    }
}
